@startuml
class Personaje
class Nave
class Alien
class AlienGrande
class AlienPequeño
class Proyectil
class BalaJugador
class BalaAlien
class Propulsor
class MotorParticulas
class Escudo
class Colisionador
class Transform
class Proyectil
class BalaJugador
class BalaAlien
class Propulsor
class MotorParticulas
class Escudo
class Colisionador
class Transform
class Partida
class Marcador
class Puntaje
class Vida
class Cronometro
class Nivel
class PowerUp
class MinaEspacial
class Satelite
class GestorSonido
class SonidoExplosion
class SonidoDisparo
PowerUp --|> Personaje
Nave --|> Personaje
Alien --|> Personaje
AlienGrande --|> Alien
AlienPequeño --|> Alien
BalaJugador --|> Proyectil
BalaAlien --|> Proyectil
AsteroideGrande --|> Asteroide
AsteroideMediano --|> Asteroide
MinaEspacial --|> Personaje
AsteroidePequeño --|> Asteroide
Satelite --|> Personaje
Nave *-- Propulsor
Nave *-- Escudo
Nave *-- MotorParticulas
Partida *-- Marcador
Partida *-- Nivel
Marcador *-- Puntaje
Marcador *-- Vida
Nave o-- Satelite
MinaEspacial o-- Asteroide
Nave o-- PowerUp
Partida o-- Nave
Partida o-- Asteroide
Partida o-- Ovni
Nave o-- BalaJugador
Alien o-- BalaAlien
Personaje o-- Colisionador
Personaje o-- Transform
GestorSonido o-- SonidoExplosion
GestorSonido o-- SonidoDisparo
Partida o-- Cronometro
Partida o-- GestorSonido
@enduml
