' --- CLASES BASE Y COMPONENTES ---
abstract class Personaje
class Transform
class Colisionador

' --- ENTIDADES PRINCIPALES ---
class Nave
class Alien
class AlienGrande
class AlienPequeño
class Ovni
class Asteroide
class AsteroideGrande
class AsteroideMediano
class AsteroidePequeño
class MinaEspacial
class Satelite

' --- OBJETOS Y PROYECTILES ---
class Proyectil
class BalaJugador
class BalaAlien
class KitReparacion
class PowerUp
class Escudo
class Propulsor
class MotorParticulas

' --- SISTEMA DE JUEGO ---
class Partida
class Marcador
class Nivel
class Cronometro
class GestorSonido
class SonidoExplosion
class SonidoDisparo

' --- HERENCIA ---
Nave --|> Personaje
Alien --|> Personaje
MinaEspacial --|> Personaje
Satelite --|> Personaje

AlienGrande --|> Alien
AlienPequeño --|> Alien

BalaJugador --|> Proyectil
BalaAlien --|> Proyectil

AsteroideGrande --|> Asteroide
AsteroideMediano --|> Asteroide
AsteroidePequeño --|> Asteroide

' --- COMPOSICIÓN (Vínculos fuertes de existencia) ---
Nave "1" *-- "1" Transform
Nave "1" *-- "1" Colisionador
Nave "1" *-- "1" Propulsor
Nave "1" *-- "1" MotorParticulas

Partida "1" *-- "1" Marcador
Partida "1" *-- "1" Cronometro
Partida "1" *-- "1" Nivel

Marcador "1" *-- "1" Puntaje
Marcador "1" *-- "1" Vida

' --- AGREGACIÓN E INTERACCIONES (Uso y acciones) ---
Nave "1" o-- "0..1" KitReparacion : Reparar()
Nave "1" o-- "0..*" PowerUp : Equipar()
Nave "1" o-- "0..1" Escudo : Activar()
Nave "1" o-- "*" BalaJugador : Disparar()

Alien "1" o-- "*" BalaAlien : Disparar()
MinaEspacial "1" o-- "1" Asteroide : Seguir()

Partida "1" o-- "1" Nave : Controlar()
Partida "1" o-- "*" Asteroide : Generar()
Partida "1" o-- "0..1" Ovni : Aparecer()
Partida "1" o-- "1" GestorSonido : Reproducir()

GestorSonido "1" o-- "*" SonidoExplosion : Ejecutar()
GestorSonido "1" o-- "*" SonidoDisparo : Ejecutar()

' --- ATRIBUTOS Y MÉTODOS ---
Personaje : vida
Personaje : Morir()

Nave : integridad
Nave : Girar()
Nave : Acelerar()

Asteroide : float velocidad
Asteroide : Dividir()

@enduml
